### ISSUE TITLE
Error Querying InfluxDb, when users are trying to monitor the transfer

### ISSUE THREAD

**Issue by jgoldverg** [didclab/ods-metadata#11]
There is an error that clients experience when trying query influx data. Here is the exception
2022-09-22 23:02:29.193  INFO 1085241 --- [nio-8084-exec-6] o.o.o.services.InfluxIOService           : Global Job 6509: size 0
2022-09-22 23:02:39.200 ERROR 1085241 --- [nio-8084-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.influxdb.exceptions.InfluxException: timeout] with root cause

java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183) ~[na:na]
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1454) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065) ~[na:na]
	at okio.InputStreamSource.read(JvmOkio.kt:93) ~[okio-2.10.0.jar!/:na]
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125) ~[okio-2.10.0.jar!/:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427) ~[okio-2.10.0.jar!/:na]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320) ~[okio-2.10.0.jar!/:na]
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at com.influxdb.client.internal.GzipInterceptor.intercept(GzipInterceptor.java:91) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at com.influxdb.client.internal.AuthenticateInterceptor.intercept(AuthenticateInterceptor.java:103) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:152) ~[logging-interceptor-3.14.9.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at com.influxdb.internal.UserAgentInterceptor.intercept(UserAgentInterceptor.java:60) ~[influxdb-client-core-6.3.0.jar!/:6.3.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar!/:na]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar!/:na]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[retrofit-2.9.0.jar!/:na]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:245) ~[influxdb-client-core-6.3.0.jar!/:6.3.0]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:198) ~[influxdb-client-core-6.3.0.jar!/:6.3.0]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:130) ~[influxdb-client-core-6.3.0.jar!/:6.3.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:204) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:147) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:134) ~[influxdb-client-java-6.3.0.jar!/:6.3.0]
	at org.onedatashare.odsmetadata.services.InfluxIOService.getUserJobVfsBucketData(InfluxIOService.java:121) ~[classes!/:0.0.1-SNAPSHOT]
	at org.onedatashare.odsmetadata.controller.BatchJobController.getJobMeasurements(BatchJobController.java:173) ~[classes!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by jgoldverg** [comment]
This was an issue with the underlying ec2 instance. After restarting this disappeared.

**Comment by jgoldverg** [comment]
This was an issue with the underlying ec2 instance. After restarting this disappeared.
